apps/event/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        route = 'eventdetail/<int:pk>/',
        view = views.EventDetailView.as_view(),
        name = 'url_eventdetail'
    ),
    path(
        route = 'allevents/',
        view = views.AllEventsView.as_view(),
        name = 'url_allevents'
    ),
]

cobija/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('apps.core.urls', 'core_app'), namespace = 'core_app')),
    path('pet/', include(('apps.pet.urls', 'pet_app'), namespace = 'pet_app')),
    path('partner/', include(('apps.partner.urls', 'partner_app'), namespace = 'partner_app')),
    path('event/', include(('apps.event.urls', 'event_app'), namespace = 'event_app')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# Custom titles for admin
admin.site.site_title = "Cobija de  Amor"
admin.site.site_header = "Cobija de Amor"

apps/event/models.py
from django.db import models
from auditlog.registry import auditlog

class Event(models.Model):
    title = models.CharField(max_length = 50, verbose_name = 'Title')
    location = models.CharField(max_length = 250, verbose_name = 'Location', help_text = 'Place of the event')
    description = models.TextField(blank = True, verbose_name = 'Description', help_text = 'Description of the event')
    link = models.URLField(max_length = 150, blank = True, verbose_name = 'Event link')
    date = models.DateField(verbose_name = 'Date', help_text = 'Date of the event')
    logo = models.ImageField(upload_to = 'events', verbose_name = 'Logo', help_text = 'Reference image')
    status = models.BooleanField(default = True, verbose_name =  'Status')
    created = models.DateTimeField(auto_now_add = True, blank = True, null = True, verbose_name = 'Creation date')
    updated = models.DateTimeField(auto_now = True, blank = True, null = True, verbose_name = 'Modification date')

    class Meta:
        db_table = "cobija_event"
        verbose_name = "Event"
        verbose_name_plural = "Events"
        ordering = ["-date"]

    def __str__(self):
        return self.title

class EventPhoto(models.Model):
    event = models.ForeignKey(to = Event, on_delete = models.CASCADE, verbose_name = 'Event')
    photo = models.ImageField(upload_to = 'events', verbose_name = 'Photo', help_text = 'Reference image')
    status = models.BooleanField(default = True, verbose_name =  'Status')
    created = models.DateTimeField(auto_now_add = True, blank = True, null = True, verbose_name = 'Creation date')
    updated = models.DateTimeField(auto_now = True, blank = True, null = True, verbose_name = 'Modification date')

    class Meta:
        db_table = "cobija_eventphoto"
        verbose_name = "EventPhoto"
        verbose_name_plural = "EventPhotos"
        ordering = ["photo"]

auditlog.register(Event)
auditlog.register(EventPhoto)

apps/event/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
)
from .models import (
    Event,
    EventPhoto,
)

class AllEventsView(ListView):
    model = Event
    queryset = Event.objects.all().filter(status = True)
    template_name = "event/all_events.html"
    context_object_name = "context_allevents"

class EventDetailView(ListView):
    model = Event
    template_name = "event/event.html"
    context_object_name = "context_eventdetail"

    def get_queryset(self, **kwargs):
        pk = self.kwargs.get('pk', None)
        queryset = self.model.objects.all()
        return queryset.filter(id = pk)

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', None)

        # EventPhoto context
        query_eventphotos = EventPhoto.objects.filter(status = True, event__pk = pk).select_related()
        context['context_eventphotos'] = query_eventphotos

        return context

templates/event/all_events.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ block.super }}{% endblock %}
{% block cssplus %}
    <style>
        .navbar-mod {
            position: absolute;
            width: 100%;
            padding: 10px 60px;
            background: #ffffff !important;
        }

        .navbar-light .navbar-nav .nav-link,
        .navbar-light .navbar-nav .nav-link:focus {
            color: #666666;
        }

        .navbar-light .navbar-nav .nav-link:hover,
        .navbar-light .navbar-nav .nav-link.active {
            color: #fbaf32;
        }
    </style>
{% endblock %}
{% block header %}{% endblock %}

{% block content %}
    <section class="bg-light pt-5 pb-5">
        <div class="container pt-5">
            <div class="section-header text-center">
                <h2>Campañas</h2>
                <p>Galería de todas las campañas</p>
            </div>
            <div class="row">
                {% for news in context_allevents %}
                <div class="col-md-3">
                    <div class="event-item">
                        <div class="floating-icon">
                            <a href="{% url 'event_app:url_eventdetail' news.id %}">
                                <img src="{{ news.logo.url }}" class="img-responsive">
                            </a>
                        </div>
                        <div>
                            <h3>{{ news.title }}</h3>
                            <div class="event-location">{{ news.location }}</div>
                            <div class="event-position">– {{ news.date }} –</div>
                            <div class="event-desc">{{ news.description|slice:"0:110" }}...</div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/event/event.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ block.super }}{% endblock %}
{% block cssplus %}
    <style>
        .navbar-mod {
            position: absolute;
            width: 100%;
            padding: 10px 60px;
            background: #ffffff !important;
        }

        .navbar-light .navbar-nav .nav-link,
        .navbar-light .navbar-nav .nav-link:focus {
            color: #666666;
        }

        .navbar-light .navbar-nav .nav-link:hover,
        .navbar-light .navbar-nav .nav-link.active {
            color: #fbaf32;
        }
    </style>
{% endblock %}
{% block header %}{% endblock %}

{% block content %}
    <section class="bg-light pt-5 pb-5">
        <div class="container pt-5">
            <div class="section-header text-center">
                <h2>Campaña</h2>
            </div>
            {% for news in context_eventdetail %}
                <div class="g-padding-y-10--xs">
                    <div class="row g-margin-b-30--xs">
                        <div class="col-sm-12">
                            <div class="g-margin-t-10--md g-margin-b-20--xs">
                                <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-letter-spacing--2 g-margin-b-20--xs text-color-base">
                                    {{ news.date|date:"DATE_FORMAT" }}
                                </p>
                                <h2 class="g-font-size-30--md">
                                    {{ news.title }}
                                </h2>
                                <p class="g-font-size-14--md">
                                    {{ news.location }}
                                </p>
                                <p class="g-font-size-15--md">
                                    {{ news.description }}
                                </p>
                                {% if news.link %}
                                <p class="g-font-size-13--md">
                                    <b>Link: </b>
                                    <a href="{{ news.link }}" target="_blank" rel="noopener noreferrer">
                                        {{ news.link }}
                                    </a>
                                </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}

            <div id="bs4-slide-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% for news in context_eventphotos %}
                        <div class="carousel-item{% if forloop.first %} active{% endif %}">
                            <img class="d-block w-100" src="{{ news.photo.url }}">
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#bs4-slide-carousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#bs4-slide-carousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascriptplus %}
    <script>
        $('#bs4-slide-carousel').carousel({
            interval: 5000
        })
    </script>
{% endblock javascriptplus %}