apps/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        route = '',
        view = views.HomeView.as_view(),
        name = 'url_home'
    ),
]

cobija/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('apps.core.urls', 'core_app'), namespace = 'core_app')),
    path('pet/', include(('apps.pet.urls', 'pet_app'), namespace = 'pet_app')),
    path('partner/', include(('apps.partner.urls', 'partner_app'), namespace = 'partner_app')),
    path('event/', include(('apps.event.urls', 'event_app'), namespace = 'event_app')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# Custom titles for admin
admin.site.site_title = "Cobija de  Amor"
admin.site.site_header = "Cobija de Amor"

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'img/cobijadeamor.png' %}" type="image/png" sizes="16x16">
    <title>{% block title %}Cobija de Amor{% endblock %}</title>
    {% include 'base/css.html' %}
    {% block cssplus %}{% endblock %}
</head>
<body id="page-top">
    {% include 'base/navbar.html' %}

    {% block header %}
    {% include 'base/header.html' %}
    {% endblock header %}

    {% block content %}

    <!-- About -->
    {% block content_about %}
    {% endblock content_about %}

    <!-- Event -->
    {% block content_events %}
    {% endblock content_events %}

    <!-- Pets -->
    {% block content_pets %}
    {% endblock content_pets %}

    <!-- Partners -->
    {% block content_partners %}
    {% endblock content_partners %}

    <!-- Members -->
    {% block content_members %}
    {% endblock content_members %}

    <!-- Links -->
    {% block content_links %}
    {% endblock content_links %}

    <!-- Contact -->
    {% block content_contact %}
    {% endblock content_contact %}

    {% endblock content %}

    <a href="#top" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

    {% include 'base/footer.html' %}
    {% include 'base/javascript.html' %}
    {% block javascriptplus %}{% endblock %}
</body>
</html>

templates/base/css.html
{% load static %}
    <!-- Bootstrap core CSS -->
    <!--<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">-->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/global.css' %}" rel="stylesheet">

    <!-- Customizer -->
    <link href="{% static 'css/customizer.css' %}" rel="stylesheet">
    <link href="{% static 'css/pets-gallery.css' %}" rel="stylesheet">

    <!-- CSS Libraries -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Nunito:600,700" rel="stylesheet">

templates/base/footer.html
{% load static %}
    <!-- Footer -->
    <footer>
        <div class="footer-bar">
            <div class="copyright">
                <div class="container">
                    <p>Copyright &copy; Cobija de Amor {% now "Y" %}.</p>
                    <p>Designed By <a href="https://github.com/glenjasper" target="_blank" rel="noopener noreferrer">GJ</a></p>
                </div>
            </div>
        </div>
    </footer>

templates/base/header.html
{% load static %}
    <!-- Header -->
    <!-- Carousel Start -->
    <div class="carousel">
        <div class="container-fluid">
            <div class="owl-carousel">
                <div class="carousel-item">
                    <div class="carousel-img">
                        <img src="{% static 'img/carousel-1.jpg' %}" alt="Image">
                    </div>
                    <div class="carousel-text">
                        <h1>Bienvenid@ <span>Cobij@lover</span></h1>
                        <p>
                            Nuestro propósito es velar por los animalitos que están pasando dificultades, encontrarles un cálido hogar, el cual ellos invadirán con todo el amor posible.
                        </p>
                        <div class="carousel-btn">
                            <a class="btn custom-btn js-scroll-trigger" href="#section_about">Saber más</a>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="carousel-img">
                        <img src="{% static 'img/carousel-2.jpg' %}" alt="Image">
                    </div>
                    <div class="carousel-text">
                        <h1>Bienvenid@ <span>Cobij@lover</span></h1>
                        <p>
                            Nuestro propósito es velar por los animalitos que están pasando dificultades, encontrarles un cálido hogar, el cual ellos invadirán con todo el amor posible.
                        </p>
                        <div class="carousel-btn">
                            <a class="btn custom-btn js-scroll-trigger" href="#section_about">Saber más</a>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="carousel-img">
                        <img src="{% static 'img/carousel-3.jpg' %}" alt="Image">
                    </div>
                    <div class="carousel-text">
                        <h1>Bienvenid@ <span>Cobij@lover</span></h1>
                        <p>
                            Nuestro propósito es velar por los animalitos que están pasando dificultades, encontrarles un cálido hogar, el cual ellos invadirán con todo el amor posible.
                        </p>
                        <div class="carousel-btn">
                            <a class="btn custom-btn js-scroll-trigger" href="#section_about">Saber más</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/base/javascript.html
{% load static %}
    <!-- Bootstrap core JavaScript -->
    <!--<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>-->
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>

    <!-- Javascript Libraries -->
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Customizer -->
    <script src="{% static 'js/customizer.js' %}"></script>

    <!-- Isotope -->
    <!--<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>-->
    <script src="{% static 'js/isotope.pkgd.js' %}"></script>

templates/base/navbar.html
{% load static %}
    <div class="navbar navbar-expand-lg navbar-light bg-light navbar-mod">
        <div class="container-fluid">
            <a class="navbar-brand page-scroll" href="{% url 'core_app:url_home' %}">
                <!--<img src="{% static 'img/cobijadeamor.png' %}">-->
                <span class="fas fa-paw"></span>
                Cobija de <span>Amor</span>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link js-scroll-trigger" {% if request.path == '/' %}href="#page-top"{% else %}href="{% url 'core_app:url_home' %}"{% endif %}>Home</a>
                    <a class="nav-item nav-link js-scroll-trigger" {% if request.path == '/' %}href="#section_about"{% else %}href="{% url 'core_app:url_home' %}#section_about"{% endif %}>Sobre nosotros</a>
                    <a class="nav-item nav-link js-scroll-trigger" {% if request.path == '/' %}href="#section_events"{% else %}href="{% url 'core_app:url_home' %}#section_events"{% endif %}>Campañas</a>
                    <a class="nav-item nav-link js-scroll-trigger" {% if request.path == '/' %}href="#section_pets"{% else %}href="{% url 'core_app:url_home' %}#section_pets"{% endif %}>Cobijitas</a>
                    <a class="nav-item nav-link js-scroll-trigger" {% if request.path == '/' %}href="#section_partners"{% else %}href="{% url 'core_app:url_home' %}#section_partners"{% endif %}>Cobijalovers</a>
                    <a class="nav-item nav-link js-scroll-trigger" {% if request.path == '/' %}href="#section_members"{% else %}href="{% url 'core_app:url_home' %}#section_members"{% endif %}>Miembros</a>
                    <!--
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Pages</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="blog.html">Blog Grid</a>
                            <a class="dropdown-item" href="single.html">Blog Detail</a>
                        </div>
                    </div>
                    -->
                    <a class="nav-item nav-link js-scroll-trigger" {% if request.path == '/' %}href="#section_contact"{% else %}href="{% url 'core_app:url_home' %}#section_contact"{% endif %}>Contacto</a>
                </div>
            </div>
        </div>
    </div>